language: node_js
addons:
    code_climate:
        repo_token:
services: mongodb
node_js:
  - "4.2.2"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - grunt exec:install
script: grunt exec:coverage
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
