language: node_js
services: mongodb
node_js:
  - "4.2.2"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - grunt exec:install
script: npm run coverage
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
