language: node_js
addons:
    code_climate:
        repo_token:
services: mongodb
node_js:
  - "4.2.2"
before_install: npm install -g grunt-cli codeclimate-test-reporter
install: npm install
before_script:
  - grunt exec:install
script: npn run coverage
after_success:
  - "cat ./coverage/lcov.info | codeclimate"
