language: node_js
services: mongodb
node_js:
  - "4.2.3"
install: npm install && npm install coveralls && npm install mocha-lcov-reporter
script: ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly tests/* -- -R spec
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
