language: node_js
services: mongodb
node_js:
  - "6.9.2"
install:
  - cd ./source
  - npm install
  - npm install coveralls
  - npm install mocha-lcov-reporter
script:
  - npm run coverageLcovOnly
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
