language: node_js
services: mongodb
node_js:
  - "4.3.1"
install:
  - cd source
  - npm install
  - npm install coveralls
  - npm install mocha-lcov-reporter
script:
  - cd source
  - npm run coverageLcovOnly
after_success:
  - cat .source/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
